### ISSUE TITLE
Compiling OpticX

### ISSUE THREAD

**Issue by bolirev** [BrainsOnBoard/compound-ray#23]
Hi, I am following your procedure to install CompoundRay on a 20.04 ubuntu machine. The cmake gives me an output, with Vulkan missing and OpenEXR missing. I am not sure whether this is critical and how to install the missing dependencies. 

The output of cmake is:
`
sutil OPTIXIR
ptx_files = /home/neurobio-bielefeld/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/SDK/build/lib/ptx/./sutil_generated_sphere.cu.optixir;/home/neurobio-bielefeld/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/SDK/build/lib/ptx/./sutil_generated_whitted.cu.optixir
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at lib/DemandLoading/docs/API/CMakeLists.txt:32 (message):
  Doxygen not found.  Skipping DemandLoading library documentation.

CMake Warning at lib/ImageSource/CMakeLists.txt:53 (message):
  OpenEXR not found (see OpenEXR_ROOT).  Will use procedural texture in
  optixDemandTexture.

-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using X11 for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: /home/neurobio-bielefeld/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/SDK/build
`

**Comment by Blayzeing** [comment]
Hi,
Neither of these are critical, and I'd really only expect Vulkan to be more necessary to build against if you were running on an AMD graphics card, OptiX should handle all GPU bindings fine itself.

The lack of OpenEXR won't really effect anything for the use purposes outlined in the paper and any standard use cases, although I will add some build instructions (and maybe an example) soon.
